-- ============================================================================
-- ZanzoJS — Recommended Database Indexes for the Universal Tuple Table
-- ============================================================================
-- These indexes significantly improve query performance for the SQL adapter.
-- Without them, EXISTS queries generated by @zanzojs/drizzle do full table scans.
--
-- New projects: use the canonical migrations shipped with @zanzojs/drizzle
-- (packages/drizzle/migrations/*.sql), which create the table and the indexes
-- idx_zanzo_unique (object, relation, subject) and idx_zanzo_subject_relation.
-- This file remains for existing tables created before those migrations.
--
-- Apply ONE of the sections below depending on your database dialect.

-- ─── SQLite ─────────────────────────────────────────────────────────────────

-- Used by: WHERE subject = ? AND relation = ?
CREATE INDEX IF NOT EXISTS idx_zanzo_subject_relation
  ON zanzo_tuples (subject, relation);

-- Used by: WHERE object = ? AND relation = ?
CREATE INDEX IF NOT EXISTS idx_zanzo_object_relation
  ON zanzo_tuples (object, relation);

-- Used by: WHERE subject = ? AND object = ?
CREATE INDEX IF NOT EXISTS idx_zanzo_subject_object
  ON zanzo_tuples (subject, object);

-- Uniqueness constraint (recommended to prevent duplicate tuples)
CREATE UNIQUE INDEX IF NOT EXISTS idx_zanzo_unique_tuple
  ON zanzo_tuples (subject, relation, object);


-- ─── PostgreSQL ─────────────────────────────────────────────────────────────

-- -- Used by: WHERE subject = $1 AND relation = $2
-- CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_zanzo_subject_relation
--   ON zanzo_tuples (subject, relation);
--
-- -- Used by: WHERE object = $1 AND relation = $2
-- CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_zanzo_object_relation
--   ON zanzo_tuples (object, relation);
--
-- -- Used by: WHERE subject = $1 AND object = $2
-- CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_zanzo_subject_object
--   ON zanzo_tuples (subject, object);
--
-- -- Uniqueness constraint (recommended to prevent duplicate tuples)
-- CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS idx_zanzo_unique_tuple
--   ON zanzo_tuples (subject, relation, object);
