/**
 * Template: API route — POST /api/grant
 * Grants a permission by inserting base + derived tuples into the database.
 */

import type { FrameworkType } from './permissions';

export function grantRouteTemplate(framework: FrameworkType): string {
  switch (framework) {
    case 'nextjs-app':
      return nextjsAppGrant();
    case 'nextjs-pages':
      return nextjsPagesGrant();
    case 'express':
      return expressGrant();
    case 'hono':
      return honoGrant();
    case 'other':
      return otherGrant();
  }
}

function nextjsAppGrant(): string {
  return `/**
 * POST /api/grant
 * Body: { subject: string, relation: string, object: string }
 * 
 * Grants a permission by inserting base + derived tuples into the database.
 * Generated by @zanzojs/cli — customize auth and DB logic for your project.
 */
import { NextRequest, NextResponse } from 'next/server';
import { expandTuples } from '@zanzojs/core';
import { schema } from '@/zanzo.config';
// TODO: Import your DB client and zanzoTuples table
// import { db } from '@/db';
// import { zanzoTuples } from '@/db/schema';
// TODO: Import your Redis client for cache invalidation
// import { redis } from '@/lib/redis';

export async function POST(request: NextRequest) {
  const { subject, relation, object } = await request.json();

  if (!subject || !relation || !object) {
    return NextResponse.json(
      { error: 'Missing required fields: subject, relation, object' },
      { status: 400 }
    );
  }

  const baseTuple = { subject, relation, object };

  const derived = await expandTuples({
    schema,
    newTuple: baseTuple,
    fetchChildren: async (parentObject, relation) => {
      // TODO: Uncomment and adjust for your DB
      // const rows = await db.select({ object: zanzoTuples.object })
      //   .from(zanzoTuples)
      //   .where(and(
      //     eq(zanzoTuples.subject, parentObject),
      //     eq(zanzoTuples.relation, relation),
      //   ));
      // return rows.map(r => r.object);
      return [];
    },
  });

  // TODO: Insert into your database
  // await db.insert(zanzoTuples).values([baseTuple, ...derived]);

  // TODO: Invalidate the snapshot cache
  // await redis.del(\\\`snapshot:\\\${subject}\\\`);

  return NextResponse.json({
    inserted: 1 + derived.length,
    base: baseTuple,
    derived,
  });
}
`;
}

function nextjsPagesGrant(): string {
  return `/**
 * POST /api/grant
 * Body: { subject: string, relation: string, object: string }
 * 
 * Grants a permission by inserting base + derived tuples into the database.
 * Generated by @zanzojs/cli — customize auth and DB logic for your project.
 */
import type { NextApiRequest, NextApiResponse } from 'next';
import { expandTuples } from '@zanzojs/core';
import { schema } from '@/zanzo.config';
// TODO: Import your DB client and zanzoTuples table

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { subject, relation, object } = req.body;

  if (!subject || !relation || !object) {
    return res.status(400).json({ error: 'Missing required fields: subject, relation, object' });
  }

  const baseTuple = { subject, relation, object };

  const derived = await expandTuples({
    schema,
    newTuple: baseTuple,
    fetchChildren: async (parentObject, relation) => {
      // TODO: Query your database for children
      return [];
    },
  });

  // TODO: Insert into your database
  // TODO: Invalidate the snapshot cache

  return res.status(200).json({
    inserted: 1 + derived.length,
    base: baseTuple,
    derived,
  });
}
`;
}

function expressGrant(): string {
  return `/**
 * POST /api/grant
 * Body: { subject: string, relation: string, object: string }
 * 
 * Grants a permission by inserting base + derived tuples into the database.
 * Generated by @zanzojs/cli — customize auth and DB logic for your project.
 */
import { Request, Response } from 'express';
import { expandTuples } from '@zanzojs/core';
import { schema } from '../zanzo.config';
// TODO: Import your DB client and zanzoTuples table

export async function grantPermission(req: Request, res: Response) {
  const { subject, relation, object } = req.body;

  if (!subject || !relation || !object) {
    return res.status(400).json({ error: 'Missing required fields: subject, relation, object' });
  }

  const baseTuple = { subject, relation, object };

  const derived = await expandTuples({
    schema,
    newTuple: baseTuple,
    fetchChildren: async (parentObject, relation) => {
      // TODO: Query your database for children
      return [];
    },
  });

  // TODO: Insert into your database
  // TODO: Invalidate the snapshot cache

  return res.status(200).json({
    inserted: 1 + derived.length,
    base: baseTuple,
    derived,
  });
}
`;
}

function honoGrant(): string {
  return `/**
 * POST /api/grant
 * Body: { subject: string, relation: string, object: string }
 * 
 * Grants a permission by inserting base + derived tuples into the database.
 * Generated by @zanzojs/cli — customize auth and DB logic for your project.
 */
import { Hono } from 'hono';
import { expandTuples } from '@zanzojs/core';
import { schema } from '../zanzo.config';
// TODO: Import your DB client and zanzoTuples table

const app = new Hono();

app.post('/api/grant', async (c) => {
  const { subject, relation, object } = await c.req.json();

  if (!subject || !relation || !object) {
    return c.json({ error: 'Missing required fields: subject, relation, object' }, 400);
  }

  const baseTuple = { subject, relation, object };

  const derived = await expandTuples({
    schema,
    newTuple: baseTuple,
    fetchChildren: async (parentObject, relation) => {
      // TODO: Query your database for children
      return [];
    },
  });

  // TODO: Insert into your database
  // TODO: Invalidate the snapshot cache

  return c.json({
    inserted: 1 + derived.length,
    base: baseTuple,
    derived,
  });
});

export default app;
`;
}

function otherGrant(): string {
  return `/**
 * POST /api/grant
 * Body: { subject: string, relation: string, object: string }
 * 
 * Grants a permission by inserting base + derived tuples into the database.
 * Generated by @zanzojs/cli — adapt this to your framework.
 */
import { expandTuples } from '@zanzojs/core';
import { schema } from './zanzo.config';
// TODO: Import your DB client and zanzoTuples table

export async function grantPermission(subject: string, relation: string, object: string) {
  const baseTuple = { subject, relation, object };

  const derived = await expandTuples({
    schema,
    newTuple: baseTuple,
    fetchChildren: async (parentObject, relation) => {
      // TODO: Query your database for children
      return [];
    },
  });

  // TODO: Insert into your database
  // TODO: Invalidate the snapshot cache

  return {
    inserted: 1 + derived.length,
    base: baseTuple,
    derived,
  };
}
`;
}
