/**
 * Template: API route — GET /api/permissions
 * Returns the compiled ZanzoJS snapshot for the authenticated user.
 */

export type FrameworkType = 'nextjs-app' | 'nextjs-pages' | 'express' | 'hono' | 'other';

export function permissionsRouteTemplate(framework: FrameworkType): string {
  switch (framework) {
    case 'nextjs-app':
      return nextjsAppPermissions();
    case 'nextjs-pages':
      return nextjsPagesPermissions();
    case 'express':
      return expressPermissions();
    case 'hono':
      return honoPermissions();
    case 'other':
      return otherPermissions();
  }
}

function nextjsAppPermissions(): string {
  return `/**
 * GET /api/permissions
 * Returns the compiled ZanzoJS snapshot for the authenticated user.
 * 
 * Generated by @zanzojs/cli — customize the auth and DB logic for your project.
 */
import { NextRequest, NextResponse } from 'next/server';
import { ZanzoEngine, createZanzoSnapshot } from '@zanzojs/core';
import { schema } from '@/zanzo.config';
// TODO: Import your DB client and zanzoTuples table
// import { db } from '@/db';
// import { zanzoTuples } from '@/db/schema';

export async function GET(request: NextRequest) {
  // TODO: Replace with your auth logic
  const userId = request.nextUrl.searchParams.get('userId');
  if (!userId) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  // TODO: Uncomment and adjust these queries for your schema
  // Load ONLY this user's tuples — never load all users
  // const userTuples = await db.select().from(zanzoTuples)
  //   .where(eq(zanzoTuples.subject, \\\`User:\\\${userId}\\\`));

  // Load structural tuples needed for nested permission paths
  // Adjust the relation name to match your schema (e.g. 'organization', 'workspace')
  // const structuralTuples = await db.select().from(zanzoTuples)
  //   .where(eq(zanzoTuples.relation, 'organization'));

  // Fresh engine per request — never reuse across requests
  const engine = new ZanzoEngine(schema);
  // engine.load([...structuralTuples, ...userTuples]);

  const snapshot = createZanzoSnapshot(engine, \\\`User:\\\${userId}\\\`);
  return NextResponse.json(snapshot);
}
`;
}

function nextjsPagesPermissions(): string {
  return `/**
 * GET /api/permissions
 * Returns the compiled ZanzoJS snapshot for the authenticated user.
 * 
 * Generated by @zanzojs/cli — customize the auth and DB logic for your project.
 */
import type { NextApiRequest, NextApiResponse } from 'next';
import { ZanzoEngine, createZanzoSnapshot } from '@zanzojs/core';
import { schema } from '@/zanzo.config';
// TODO: Import your DB client and zanzoTuples table

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // TODO: Replace with your auth logic
  const userId = req.query['userId'] as string | undefined;
  if (!userId) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  // Fresh engine per request — never reuse across requests
  const engine = new ZanzoEngine(schema);
  // TODO: Load tuples from your database
  // engine.load([...structuralTuples, ...userTuples]);

  const snapshot = createZanzoSnapshot(engine, \\\`User:\\\${userId}\\\`);
  return res.status(200).json(snapshot);
}
`;
}

function expressPermissions(): string {
  return `/**
 * GET /api/permissions
 * Returns the compiled ZanzoJS snapshot for the authenticated user.
 * 
 * Generated by @zanzojs/cli — customize the auth and DB logic for your project.
 */
import { Request, Response } from 'express';
import { ZanzoEngine, createZanzoSnapshot } from '@zanzojs/core';
import { schema } from '../zanzo.config';
// TODO: Import your DB client and zanzoTuples table

export async function getPermissions(req: Request, res: Response) {
  // TODO: Replace with your auth logic
  const userId = req.query['userId'] as string | undefined;
  if (!userId) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  // Fresh engine per request — never reuse across requests
  const engine = new ZanzoEngine(schema);
  // TODO: Load tuples from your database
  // engine.load([...structuralTuples, ...userTuples]);

  const snapshot = createZanzoSnapshot(engine, \\\`User:\\\${userId}\\\`);
  return res.status(200).json(snapshot);
}
`;
}

function honoPermissions(): string {
  return `/**
 * GET /api/permissions
 * Returns the compiled ZanzoJS snapshot for the authenticated user.
 * 
 * Generated by @zanzojs/cli — customize the auth and DB logic for your project.
 */
import { Hono } from 'hono';
import { ZanzoEngine, createZanzoSnapshot } from '@zanzojs/core';
import { schema } from '../zanzo.config';
// TODO: Import your DB client and zanzoTuples table

const app = new Hono();

app.get('/api/permissions', async (c) => {
  // TODO: Replace with your auth logic
  const userId = c.req.query('userId');
  if (!userId) {
    return c.json({ error: 'Unauthorized' }, 401);
  }

  // Fresh engine per request — never reuse across requests
  const engine = new ZanzoEngine(schema);
  // TODO: Load tuples from your database
  // engine.load([...structuralTuples, ...userTuples]);

  const snapshot = createZanzoSnapshot(engine, \\\`User:\\\${userId}\\\`);
  return c.json(snapshot);
});

export default app;
`;
}

function otherPermissions(): string {
  return `/**
 * GET /api/permissions
 * Returns the compiled ZanzoJS snapshot for the authenticated user.
 * 
 * Generated by @zanzojs/cli — customize the auth and DB logic for your project.
 * Adapt this to your framework.
 */
import { ZanzoEngine, createZanzoSnapshot } from '@zanzojs/core';
import { schema } from './zanzo.config';
// TODO: Import your DB client and zanzoTuples table

export async function getPermissions(userId: string) {
  // Fresh engine per request — never reuse across requests
  const engine = new ZanzoEngine(schema);
  // TODO: Load tuples from your database
  // engine.load([...structuralTuples, ...userTuples]);

  return createZanzoSnapshot(engine, \\\`User:\\\${userId}\\\`);
}
`;
}
