/**
 * Template: API route — GET /api/permissions
 * Returns the compiled ZanzoJS snapshot for the authenticated user.
 */

export type FrameworkType = 'nextjs-app' | 'nextjs-pages' | 'express' | 'hono' | 'other';

export function permissionsRouteTemplate(framework: FrameworkType, orm: string): string {
  switch (framework) {
    case 'nextjs-app':
      return nextjsAppPermissions(orm);
    case 'nextjs-pages':
      return nextjsPagesPermissions(orm);
    case 'express':
      return expressPermissions(orm);
    case 'hono':
      return honoPermissions(orm);
    case 'other':
      return otherPermissions(orm);
  }
}

function getBoilerplate(orm: string) {
  if (orm === 'drizzle') {
    return {
      imports: `import { createAdapter } from '@zanzojs/drizzle';\n// TODO: Import your DB client and zanzoTuples table\n// import { db } from '@/db';\n// import { zanzoTuples } from '@/db/schema';`,
      body: `  // The Zanzo Drizzle adapter automatically pulls tuples and executes recursive graphs\n  const adapter = createAdapter(db, { tuples: zanzoTuples }, schema);\n  const snapshot = await adapter.snapshot(\\\`User:\\\${userId}\\\`);`
    };
  }
  return {
    imports: `import { ZanzoEngine, createZanzoSnapshot } from '@zanzojs/core';\n// TODO: Import your DB client and zanzoTuples table\n// import { db } from '@/db';\n// import { zanzoTuples } from '@/db/schema';`,
    body: `  // TODO: Build your manual tuples fetch queries or USE AN ADAPTER like @zanzojs/drizzle\n  // const userTuples = await db.select()...;\n  // const structuralTuples = await db.select()...;\n\n  // Fresh engine per request — never reuse across requests\n  const engine = new ZanzoEngine(schema);\n  // engine.load([...structuralTuples, ...userTuples]);\n\n  const snapshot = createZanzoSnapshot(engine, \\\`User:\\\${userId}\\\`);`
  };
}

function nextjsAppPermissions(orm: string): string {
  const bp = getBoilerplate(orm);
  return `/**
 * GET /api/permissions
 * Returns the compiled ZanzoJS snapshot for the authenticated user.
 * 
 * Generated by @zanzojs/cli.
 */
import { NextRequest, NextResponse } from 'next/server';
import { schema } from '@/zanzo.config';
${bp.imports}

export async function GET(request: NextRequest) {
  // TODO: Replace with your auth logic
  const userId = request.nextUrl.searchParams.get('userId');
  if (!userId) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

${bp.body}

  return NextResponse.json(snapshot);
}
`;
}

function nextjsPagesPermissions(orm: string): string {
  const bp = getBoilerplate(orm);
  return `/**
 * GET /api/permissions
 * Returns the compiled ZanzoJS snapshot for the authenticated user.
 * 
 * Generated by @zanzojs/cli.
 */
import type { NextApiRequest, NextApiResponse } from 'next';
import { schema } from '@/zanzo.config';
${bp.imports}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // TODO: Replace with your auth logic
  const userId = req.query['userId'] as string | undefined;
  if (!userId) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

${bp.body}

  return res.status(200).json(snapshot);
}
`;
}

function expressPermissions(orm: string): string {
  const bp = getBoilerplate(orm);
  return `/**
 * GET /api/permissions
 * Returns the compiled ZanzoJS snapshot for the authenticated user.
 * 
 * Generated by @zanzojs/cli.
 */
import { Request, Response } from 'express';
import { schema } from '../zanzo.config';
${bp.imports}

export async function getPermissions(req: Request, res: Response) {
  // TODO: Replace with your auth logic
  const userId = req.query['userId'] as string | undefined;
  if (!userId) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

${bp.body}

  return res.status(200).json(snapshot);
}
`;
}

function honoPermissions(orm: string): string {
  const bp = getBoilerplate(orm);
  return `/**
 * GET /api/permissions
 * Returns the compiled ZanzoJS snapshot for the authenticated user.
 * 
 * Generated by @zanzojs/cli.
 */
import { Hono } from 'hono';
import { schema } from '../zanzo.config';
${bp.imports}

const app = new Hono();

app.get('/api/permissions', async (c) => {
  // TODO: Replace with your auth logic
  const userId = c.req.query('userId');
  if (!userId) {
    return c.json({ error: 'Unauthorized' }, 401);
  }

${bp.body}

  return c.json(snapshot);
});

export default app;
`;
}

function otherPermissions(orm: string): string {
  const bp = getBoilerplate(orm);
  return `/**
 * GET /api/permissions
 * Returns the compiled ZanzoJS snapshot for the authenticated user.
 * 
 * Generated by @zanzojs/cli — adapt this to your framework.
 */
import { schema } from './zanzo.config';
${bp.imports}

export async function getPermissions(userId: string) {
${bp.body}

  return snapshot;
}
`;
}
