/**
 * Template: API route — POST /api/revoke
 * Revokes a permission by deleting base + derived tuples from the database.
 */

import type { FrameworkType } from './permissions';

export function revokeRouteTemplate(framework: FrameworkType): string {
  switch (framework) {
    case 'nextjs-app':
      return nextjsAppRevoke();
    case 'nextjs-pages':
      return nextjsPagesRevoke();
    case 'express':
      return expressRevoke();
    case 'hono':
      return honoRevoke();
    case 'other':
      return otherRevoke();
  }
}

function nextjsAppRevoke(): string {
  return `/**
 * POST /api/revoke
 * Body: { subject: string, relation: string, object: string }
 * 
 * Revokes a permission by deleting base + derived tuples from the database.
 * Generated by @zanzojs/cli — customize auth and DB logic for your project.
 */
import { NextRequest, NextResponse } from 'next/server';
import { collapseTuples } from '@zanzojs/core';
import { schema } from '@/zanzo.config';
// TODO: Import your DB client and zanzoTuples table
// import { db } from '@/db';
// import { zanzoTuples } from '@/db/schema';
// TODO: Import your Redis client for cache invalidation
// import { redis } from '@/lib/redis';

export async function POST(request: NextRequest) {
  const { subject, relation, object } = await request.json();

  if (!subject || !relation || !object) {
    return NextResponse.json(
      { error: 'Missing required fields: subject, relation, object' },
      { status: 400 }
    );
  }

  const baseTuple = { subject, relation, object };

  const derived = await collapseTuples({
    schema,
    revokedTuple: baseTuple,
    fetchChildren: async (parentObject, relation) => {
      // TODO: Uncomment and adjust for your DB
      // const rows = await db.select({ object: zanzoTuples.object })
      //   .from(zanzoTuples)
      //   .where(and(
      //     eq(zanzoTuples.subject, parentObject),
      //     eq(zanzoTuples.relation, relation),
      //   ));
      // return rows.map(r => r.object);
      return [];
    },
  });

  // TODO: Delete from your database
  // for (const tuple of [baseTuple, ...derived]) {
  //   await db.delete(zanzoTuples).where(and(
  //     eq(zanzoTuples.subject, tuple.subject),
  //     eq(zanzoTuples.relation, tuple.relation),
  //     eq(zanzoTuples.object, tuple.object),
  //   ));
  // }

  // TODO: Invalidate the snapshot cache
  // await redis.del(\\\`snapshot:\\\${subject}\\\`);

  return NextResponse.json({
    deleted: 1 + derived.length,
    base: baseTuple,
    derived,
  });
}
`;
}

function nextjsPagesRevoke(): string {
  return `/**
 * POST /api/revoke
 * Body: { subject: string, relation: string, object: string }
 * 
 * Revokes a permission by deleting base + derived tuples from the database.
 * Generated by @zanzojs/cli — customize auth and DB logic for your project.
 */
import type { NextApiRequest, NextApiResponse } from 'next';
import { collapseTuples } from '@zanzojs/core';
import { schema } from '@/zanzo.config';
// TODO: Import your DB client and zanzoTuples table

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { subject, relation, object } = req.body;

  if (!subject || !relation || !object) {
    return res.status(400).json({ error: 'Missing required fields: subject, relation, object' });
  }

  const baseTuple = { subject, relation, object };

  const derived = await collapseTuples({
    schema,
    revokedTuple: baseTuple,
    fetchChildren: async (parentObject, relation) => {
      // TODO: Query your database for children
      return [];
    },
  });

  // TODO: Delete from your database
  // TODO: Invalidate the snapshot cache

  return res.status(200).json({
    deleted: 1 + derived.length,
    base: baseTuple,
    derived,
  });
}
`;
}

function expressRevoke(): string {
  return `/**
 * POST /api/revoke
 * Body: { subject: string, relation: string, object: string }
 * 
 * Revokes a permission by deleting base + derived tuples from the database.
 * Generated by @zanzojs/cli — customize auth and DB logic for your project.
 */
import { Request, Response } from 'express';
import { collapseTuples } from '@zanzojs/core';
import { schema } from '../zanzo.config';
// TODO: Import your DB client and zanzoTuples table

export async function revokePermission(req: Request, res: Response) {
  const { subject, relation, object } = req.body;

  if (!subject || !relation || !object) {
    return res.status(400).json({ error: 'Missing required fields: subject, relation, object' });
  }

  const baseTuple = { subject, relation, object };

  const derived = await collapseTuples({
    schema,
    revokedTuple: baseTuple,
    fetchChildren: async (parentObject, relation) => {
      // TODO: Query your database for children
      return [];
    },
  });

  // TODO: Delete from your database
  // TODO: Invalidate the snapshot cache

  return res.status(200).json({
    deleted: 1 + derived.length,
    base: baseTuple,
    derived,
  });
}
`;
}

function honoRevoke(): string {
  return `/**
 * POST /api/revoke
 * Body: { subject: string, relation: string, object: string }
 * 
 * Revokes a permission by deleting base + derived tuples from the database.
 * Generated by @zanzojs/cli — customize auth and DB logic for your project.
 */
import { Hono } from 'hono';
import { collapseTuples } from '@zanzojs/core';
import { schema } from '../zanzo.config';
// TODO: Import your DB client and zanzoTuples table

const app = new Hono();

app.post('/api/revoke', async (c) => {
  const { subject, relation, object } = await c.req.json();

  if (!subject || !relation || !object) {
    return c.json({ error: 'Missing required fields: subject, relation, object' }, 400);
  }

  const baseTuple = { subject, relation, object };

  const derived = await collapseTuples({
    schema,
    revokedTuple: baseTuple,
    fetchChildren: async (parentObject, relation) => {
      // TODO: Query your database for children
      return [];
    },
  });

  // TODO: Delete from your database
  // TODO: Invalidate the snapshot cache

  return c.json({
    deleted: 1 + derived.length,
    base: baseTuple,
    derived,
  });
});

export default app;
`;
}

function otherRevoke(): string {
  return `/**
 * POST /api/revoke
 * Body: { subject: string, relation: string, object: string }
 * 
 * Revokes a permission by deleting base + derived tuples from the database.
 * Generated by @zanzojs/cli — adapt this to your framework.
 */
import { collapseTuples } from '@zanzojs/core';
import { schema } from './zanzo.config';
// TODO: Import your DB client and zanzoTuples table

export async function revokePermission(subject: string, relation: string, object: string) {
  const baseTuple = { subject, relation, object };

  const derived = await collapseTuples({
    schema,
    revokedTuple: baseTuple,
    fetchChildren: async (parentObject, relation) => {
      // TODO: Query your database for children
      return [];
    },
  });

  // TODO: Delete from your database
  // TODO: Invalidate the snapshot cache

  return {
    deleted: 1 + derived.length,
    base: baseTuple,
    derived,
  };
}
`;
}
