/**
 * Template: API route — POST /api/revoke
 * Revokes a permission by deleting base + derived tuples from the database.
 */

import type { FrameworkType } from './permissions';

export function revokeRouteTemplate(framework: FrameworkType, orm: string): string {
  switch (framework) {
    case 'nextjs-app':
      return nextjsAppRevoke(orm);
    case 'nextjs-pages':
      return nextjsPagesRevoke(orm);
    case 'express':
      return expressRevoke(orm);
    case 'hono':
      return honoRevoke(orm);
    case 'other':
      return otherRevoke(orm);
  }
}

function getRevokeBoilerplate(orm: string) {
  if (orm === 'drizzle') {
    return {
      imports: `import { createAdapter } from '@zanzojs/drizzle';\n// TODO: Import your DB client and zanzoTuples table\n// import { db } from '@/db';\n// import { zanzoTuples } from '@/db/schema';`,
      body: `  // The Zanzo Adapter automatically handles recursive deletion graphs and cascade DB executions\n  const adapter = createAdapter(db, { tuples: zanzoTuples }, schema);\n  await adapter.revoke(subject, relation, object);\n\n  // TODO: Invalidate the snapshot cache\n  // await redis.del(\\\`snapshot:\\\${subject}\\\`);`
    };
  }
  return {
    imports: `import { collapseTuples } from '@zanzojs/core';\n// TODO: Import your DB client and zanzoTuples table`,
    body: `  const baseTuple = { subject, relation, object };\n\n  // WARNING: collapseTuples is a legacy low-level API. Consider using an official Adapter like @zanzojs/drizzle instead.\n  const derived = await collapseTuples({\n    schema,\n    revokedTuple: baseTuple,\n    fetchChildren: async (parentObject, relation) => {\n      // TODO: Query your database for structural children\n      return [];\n    },\n  });\n\n  // TODO: Delete generated tuples from your database manually\n  // TODO: Invalidate the snapshot cache`
  };
}

function nextjsAppRevoke(orm: string): string {
  const bp = getRevokeBoilerplate(orm);
  return `/**
 * POST /api/revoke
 * Body: { subject: string, relation: string, object: string }
 * 
 * Generated by @zanzojs/cli.
 */
import { NextRequest, NextResponse } from 'next/server';
import { schema } from '@/zanzo.config';
${bp.imports}
// TODO: Import your Redis client for cache invalidation
// import { redis } from '@/lib/redis';

export async function POST(request: NextRequest) {
  const { subject, relation, object } = await request.json();

  if (!subject || !relation || !object) {
    return NextResponse.json(
      { error: 'Missing required fields: subject, relation, object' },
      { status: 400 }
    );
  }

${bp.body}

  return NextResponse.json({ success: true, base: { subject, relation, object } });
}
`;
}

function nextjsPagesRevoke(orm: string): string {
  const bp = getRevokeBoilerplate(orm);
  return `/**
 * POST /api/revoke
 * Body: { subject: string, relation: string, object: string }
 * 
 * Generated by @zanzojs/cli.
 */
import type { NextApiRequest, NextApiResponse } from 'next';
import { schema } from '@/zanzo.config';
${bp.imports}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { subject, relation, object } = req.body;

  if (!subject || !relation || !object) {
    return res.status(400).json({ error: 'Missing required fields: subject, relation, object' });
  }

${bp.body}

  return res.status(200).json({ success: true, base: { subject, relation, object } });
}
`;
}

function expressRevoke(orm: string): string {
  const bp = getRevokeBoilerplate(orm);
  return `/**
 * POST /api/revoke
 * Body: { subject: string, relation: string, object: string }
 * 
 * Generated by @zanzojs/cli.
 */
import { Request, Response } from 'express';
import { schema } from '../zanzo.config';
${bp.imports}

export async function revokePermission(req: Request, res: Response) {
  const { subject, relation, object } = req.body;

  if (!subject || !relation || !object) {
    return res.status(400).json({ error: 'Missing required fields: subject, relation, object' });
  }

${bp.body}

  return res.status(200).json({ success: true, base: { subject, relation, object } });
}
`;
}

function honoRevoke(orm: string): string {
  const bp = getRevokeBoilerplate(orm);
  return `/**
 * POST /api/revoke
 * Body: { subject: string, relation: string, object: string }
 * 
 * Generated by @zanzojs/cli.
 */
import { Hono } from 'hono';
import { schema } from '../zanzo.config';
${bp.imports}

const app = new Hono();

app.post('/api/revoke', async (c) => {
  const { subject, relation, object } = await c.req.json();

  if (!subject || !relation || !object) {
    return c.json({ error: 'Missing required fields: subject, relation, object' }, 400);
  }

${bp.body}

  return c.json({ success: true, base: { subject, relation, object } });
});

export default app;
`;
}

function otherRevoke(orm: string): string {
  const bp = getRevokeBoilerplate(orm);
  return `/**
 * POST /api/revoke
 * Body: { subject: string, relation: string, object: string }
 * 
 * Generated by @zanzojs/cli — adapt this to your framework.
 */
import { schema } from './zanzo.config';
${bp.imports}

export async function revokePermission(subject: string, relation: string, object: string) {
${bp.body}

  return { success: true, base: { subject, relation, object } };
}
`;
}
