/**
 * Template: zanzo-migration.sql
 * The tuple store tables for @zanzojs/sql, generated by the package itself so they never drift.
 */
import { migrationSql } from '@zanzojs/sql';

export type DatabaseType = 'postgresql' | 'sqlite';

export function migrationTemplate(database: DatabaseType): string {
  const header =
    database === 'postgresql'
      ? '-- ZanzoJS tuple store (@zanzojs/sql) — PostgreSQL\n-- psql -d your_database -f zanzo-migration.sql\n\n'
      : '-- ZanzoJS tuple store (@zanzojs/sql) — SQLite / Cloudflare D1\n-- sqlite3 your.db < zanzo-migration.sql\n-- wrangler d1 execute YOUR_DB --file=zanzo-migration.sql\n\n';
  return header + migrationSql(database === 'postgresql' ? 'postgres' : 'sqlite');
}
