/**
 * Template: zanzo-migration.sql
 * Generates the Universal Tuple Table migration for the selected database.
 */

export type DatabaseType = 'postgresql' | 'sqlite' | 'mysql';

export function migrationTemplate(database: DatabaseType): string {
  switch (database) {
    case 'postgresql':
      return postgresqlMigration();
    case 'sqlite':
      return sqliteMigration();
    case 'mysql':
      return mysqlMigration();
  }
}

function postgresqlMigration(): string {
  return `-- ZanzoJS Universal Tuple Table
-- Generated by @zanzojs/cli
-- Run this migration manually: psql -d your_database -f zanzo-migration.sql

CREATE TABLE IF NOT EXISTS zanzo_tuples (
  id SERIAL PRIMARY KEY,
  object   TEXT NOT NULL,
  relation TEXT NOT NULL,
  subject  TEXT NOT NULL,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for loading a user's tuples (most common query)
CREATE INDEX IF NOT EXISTS idx_zanzo_subject ON zanzo_tuples (subject);

-- Index for structural tuple queries
CREATE INDEX IF NOT EXISTS idx_zanzo_relation ON zanzo_tuples (relation);

-- Unique constraint to prevent duplicate tuples
CREATE UNIQUE INDEX IF NOT EXISTS idx_zanzo_unique 
  ON zanzo_tuples (object, relation, subject);
`;
}

function sqliteMigration(): string {
  return `-- ZanzoJS Universal Tuple Table
-- Generated by @zanzojs/cli
-- Run this migration manually:
--   SQLite:        sqlite3 your.db < zanzo-migration.sql
--   Cloudflare D1: wrangler d1 execute YOUR_DB --file=zanzo-migration.sql

CREATE TABLE IF NOT EXISTS zanzo_tuples (
  id       INTEGER PRIMARY KEY AUTOINCREMENT,
  object   TEXT NOT NULL,
  relation TEXT NOT NULL,
  subject  TEXT NOT NULL,
  expires_at INTEGER,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE INDEX IF NOT EXISTS idx_zanzo_subject  ON zanzo_tuples (subject);
CREATE INDEX IF NOT EXISTS idx_zanzo_relation ON zanzo_tuples (relation);
CREATE UNIQUE INDEX IF NOT EXISTS idx_zanzo_unique 
  ON zanzo_tuples (object, relation, subject);
`;
}

function mysqlMigration(): string {
  return `-- ZanzoJS Universal Tuple Table
-- Generated by @zanzojs/cli
-- Run this migration manually: mysql -u root -p your_database < zanzo-migration.sql

CREATE TABLE IF NOT EXISTS zanzo_tuples (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  object     VARCHAR(255) NOT NULL,
  relation   VARCHAR(255) NOT NULL,
  subject    VARCHAR(255) NOT NULL,
  expires_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index for loading a user's tuples (most common query)
CREATE INDEX idx_zanzo_subject ON zanzo_tuples (subject);

-- Index for structural tuple queries
CREATE INDEX idx_zanzo_relation ON zanzo_tuples (relation);

-- Unique constraint to prevent duplicate tuples
CREATE UNIQUE INDEX idx_zanzo_unique 
  ON zanzo_tuples (object, relation, subject);
`;
}
