/**
 * Template: zanzo.config.ts
 * Generates a ZanzoJS schema configuration from user-specified entities.
 */

export function schemaTemplate(entities: string[]): string {
  const entityBlocks = entities.map((entity, index) => {
    if (index === 0) {
      // First entity: simple, no actions or relations (e.g. User)
      return `  .entity('${entity}', {
    actions: [] as const,
    relations: {},
  })`;
    }

    if (index === 1) {
      // Second entity: organization-style with manage action
      const firstEntity = entities[0]!;
      return `  .entity('${entity}', {
    actions: ['manage'] as const,
    relations: {
      admin: '${firstEntity}',
      member: '${firstEntity}',
    },
    permissions: {
      manage: ['admin'],
    },
  })`;
    }

    // Third+ entities: full CRUD with cross-entity relations
    const firstEntity = entities[0]!;
    const secondEntity = entities[1]!;
    return `  .entity('${entity}', {
    actions: ['create', 'read', 'update', 'delete'] as const,
    relations: {
      ${secondEntity.toLowerCase()}: '${secondEntity}',
      manager: '${firstEntity}',
      editor: '${firstEntity}',
      viewer: '${firstEntity}',
    },
    permissions: {
      create: ['manager', '${secondEntity.toLowerCase()}.admin'],
      read:   ['manager', 'editor', 'viewer', '${secondEntity.toLowerCase()}.admin'],
      update: ['manager', 'editor', '${secondEntity.toLowerCase()}.admin'],
      delete: ['manager', '${secondEntity.toLowerCase()}.admin'],
    },
  })`;
  });

  return `import { ZanzoBuilder, ZanzoEngine } from '@zanzojs/core';

/**
 * ZanzoJS Schema
 * Generated by @zanzojs/cli — customize to fit your domain.
 * 
 * Docs: https://github.com/GonzaloJeria/zanzo
 */
export const schema = new ZanzoBuilder()
${entityBlocks.join('\n')}
  .build();

// Reuse this instance across all requests for schema access only.
// Always create a fresh ZanzoEngine per request for permission evaluation.
export const schemaInstance = schema;
`;
}
